services:
  web:
    build: ./backend
    container_name: buddy_web
    command: python -m uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    env_file:
      - ./backend/.env
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres:16
    container_name: buddy_db
    restart: always
    env_file:
      - ./backend/.env
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 5s
      timeout: 5s
      retries: 5

# for development
  mailhog:
    image: mailhog/mailhog
    container_name: buddy_mailhog
    ports:
      - "1025:1025"
      - "587:587"
      - "8025:8025"
  # postgres data is stored in a named volume called postgres_data.
volumes:
  postgres_data:
