MEDITERRANEAN_FISH = [
    {"he_name": "דקר הסלעים (לוקוס אדום)", "en_name": "Dusky Grouper"},
    {"he_name": "דקר המכמורת (לוקוס לבן)", "en_name": "White Grouper"},
    {"he_name": "דוקרנית אדומה (לוקוס אירדי)", "en_name": "Mottled Grouper"},
    {"he_name": "פארידה", "en_name": "Bluespotted seabream"},
    {"he_name": "תוכי (תוכינון האוכפים)", "en_name": "Blue-barred parrotfish"},
    {"he_name": "נצרן ים תיכוני", "en_name": "Grey triggerfish"},
    {"he_name": "שטוח-ראש הודי", "en_name": "Bartail flathead"},
    {"he_name": "ספרוס הפסים (מלכה)", "en_name": "Redbanded seabream"},
    {"he_name": "חזון אדור (עספור)", "en_name": "Sharpsnout seabream"},
    {"he_name": "שינן הניבים (דנטקס)", "en_name": "Common dentex"},
    {"he_name": "סרגוס מסורטט", "en_name": "White Seabream"},
    {"he_name": "סרגוס הפסים (פיג'מה/חדד)", "en_name": "Zebra seabream"},
    {"he_name": "דניס (צ'יפורה)", "en_name": "Gilt-head Bream"},
    {"he_name": "קיפון בורי", "en_name": "Flathead Grey Mullet"},
    {"he_name": "אוכם גדול קוץ (סאינס)", "en_name": "Brown meagre"},
    {"he_name": "אראס (סיכן)", "en_name": "Rabbitfish"},
    {"he_name": "גומבר", "en_name": "Bluefish"},
    {"he_name": "אינטיאס (שולה)", "en_name": "Greater Amberjack"},
    {"he_name": "פלמידה אדומה", "en_name": "Little Tunny"},
    {"he_name": "פלמידה לבנה", "en_name": "Spanish mackerel"},
    {"he_name": "אספירנה פסוסה (ברקודה)", "en_name": "Barracuda"},
    {"he_name": "מליטה", "en_name": "Yellowmouth barracuda"},
    {"he_name": "יבלן האדווה (לבט)", "en_name": "Shi drum"},
    {"he_name": "טרכון", "en_name": "Blue Runner"},
    {"he_name": "צנינית שיננית (טרולוס/אריצולה)", "en_name": "White trevally"},
    {"he_name": "דבשתן ים-תיכוני (בן גוריון)", "en_name": "Alexandria pompano"},
    {"he_name": "מולית הפסים (ברבוניה)", "en_name": "Striped red mullet"},
    {"he_name": "לברק", "en_name": "European Seabass"},
    {"he_name": "שישן מסורטט (מרמיר)", "en_name": "Sand steenbras"},
    {"he_name": "טונה כחולת סנפיר", "en_name": "Blufin tuna"},
    {"he_name": "בינתן פורסקל", "en_name": "Red Sea goatfish"},
    {"he_name": "זהרון הדור", "en_name": "Lionfish"},
    {"he_name": "אריען", "en_name": "Leerfish"},
    {"he_name": "וואהו", "en_name": "Wahoo"},
    {"he_name": "מוסר ים", "en_name": "Red drum / Mulloway"},
]
