"""rename file_key to public_id in catch_media

Revision ID: 0ebd74ee0c76
Revises: c3659e507b43
Create Date: 2026-03-27 15:56:07.869755

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0ebd74ee0c76'
down_revision: Union[str, Sequence[str], None] = 'c3659e507b43'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('catch_media', sa.Column('public_id', sa.String(), nullable=False))
    op.drop_column('catch_media', 'file_key')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('catch_media', sa.Column('file_key', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('catch_media', 'public_id')
    # ### end Alembic commands ###
