"""Add EnvironmentalCondition table and coordinates to Session

Revision ID: 8994ff8aa9ee
Revises: 565f40f08740
Create Date: 2026-03-25 10:10:37.220487

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8994ff8aa9ee'
down_revision: Union[str, Sequence[str], None] = '565f40f08740'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('environmental_condition',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('weather_status', sa.String(), nullable=True),
    sa.Column('air_temperature', sa.Float(), nullable=True),
    sa.Column('water_temperature', sa.Float(), nullable=True),
    sa.Column('atmospheric_pressure', sa.Float(), nullable=True),
    sa.Column('moon_phase', sa.String(), nullable=True),
    sa.Column('wind_speed', sa.Float(), nullable=True),
    sa.Column('wind_direction', sa.Float(), nullable=True),
    sa.Column('current_direction', sa.Float(), nullable=True),
    sa.Column('current_speed', sa.Float(), nullable=True),
    sa.Column('wave_height', sa.Float(), nullable=True),
    sa.Column('wave_direction', sa.Float(), nullable=True),
    sa.Column('tide_status', sa.String(), nullable=True),
    sa.Column('tide_height', sa.Float(), nullable=True),
    sa.Column('tide_type', sa.String(), nullable=True),
    sa.Column('cloud_cover', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['session.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('session_id')
    )
    op.add_column('session', sa.Column('latitude', sa.Float(), nullable=True))
    op.add_column('session', sa.Column('longitude', sa.Float(), nullable=True))
    op.alter_column('user', 'joined_at',
               existing_type=sa.DATE(),
               type_=sa.DateTime(),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'joined_at',
               existing_type=sa.DateTime(),
               type_=sa.DATE(),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_column('session', 'longitude')
    op.drop_column('session', 'latitude')
    op.drop_table('environmental_condition')
    # ### end Alembic commands ###
