"""add_tracking_counts_to_user_insight

Revision ID: 2285284b4b52
Revises: 0ebd74ee0c76
Create Date: 2026-04-18 11:03:17.929123

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2285284b4b52'
down_revision: Union[str, Sequence[str], None] = '0ebd74ee0c76'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_insight', sa.Column('last_analyzed_sessions', sa.Integer(), nullable=True))
    op.add_column('user_insight', sa.Column('last_analyzed_catches', sa.Integer(), nullable=True))
    
    # Set default for existing rows
    op.execute("UPDATE user_insight SET last_analyzed_sessions = 0, last_analyzed_catches = 0")
    
    # Make columns NOT NULL
    op.alter_column('user_insight', 'last_analyzed_sessions', nullable=False)
    op.alter_column('user_insight', 'last_analyzed_catches', nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_insight', 'last_analyzed_catches')
    op.drop_column('user_insight', 'last_analyzed_sessions')
    # ### end Alembic commands ###
