"""Add chat tables

Revision ID: 565f40f08740
Revises: 9b3f462c020d
Create Date: 2026-03-15 15:21:53.247752

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '565f40f08740'
down_revision: Union[str, Sequence[str], None] = '9b3f462c020d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chat_room',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('is_group', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('guest',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('display_name', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('chat_participant',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('room_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('guest_id', sa.UUID(), nullable=True),
    sa.Column('joined_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['guest_id'], ['guest.id'], ),
    sa.ForeignKeyConstraint(['room_id'], ['chat_room.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('message',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('room_id', sa.UUID(), nullable=False),
    sa.Column('sender_id', sa.UUID(), nullable=True),
    sa.Column('guest_id', sa.UUID(), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['guest_id'], ['guest.id'], ),
    sa.ForeignKeyConstraint(['room_id'], ['chat_room.id'], ),
    sa.ForeignKeyConstraint(['sender_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.alter_column('catch', 'free_text',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.drop_index(op.f('idx_catch_fish_id'), table_name='catch')
    op.drop_index(op.f('idx_catch_id'), table_name='catch')
    op.drop_index(op.f('idx_catch_session_id'), table_name='catch')
    op.drop_index(op.f('idx_catch_user_id'), table_name='catch', postgresql_with={'deduplicate_items': 'true'})
    op.alter_column('fish', 'he_name',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('fish', 'en_name',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               nullable=False)
    op.alter_column('session', 'free_text',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               nullable=False)
    op.alter_column('session', 'longest_hold_down_time',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('session', 'longest_hold_down_depth',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('session', 'entry_time',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False)
    op.alter_column('session', 'exit_time',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False)
    op.drop_index(op.f('idx_session_user_id'), table_name='session')
    op.alter_column('user', 'first_name',
               existing_type=sa.TEXT(),
               type_=sa.String(length=50),
               existing_nullable=False)
    op.alter_column('user', 'last_name',
               existing_type=sa.TEXT(),
               type_=sa.String(length=50),
               existing_nullable=False)
    op.alter_column('user', 'user_name',
               existing_type=sa.TEXT(),
               type_=sa.String(length=30),
               existing_nullable=False)
    op.alter_column('user', 'password',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('user', 'joined_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.Date(),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('user', 'email',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('user', 'phone_number',
               existing_type=sa.TEXT(),
               type_=sa.String(length=15),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'phone_number',
               existing_type=sa.String(length=15),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('user', 'email',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('user', 'joined_at',
               existing_type=sa.Date(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('user', 'password',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('user', 'user_name',
               existing_type=sa.String(length=30),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('user', 'last_name',
               existing_type=sa.String(length=50),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('user', 'first_name',
               existing_type=sa.String(length=50),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.create_index(op.f('idx_session_user_id'), 'session', ['user_id'], unique=False)
    op.alter_column('session', 'exit_time',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True)
    op.alter_column('session', 'entry_time',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True)
    op.alter_column('session', 'longest_hold_down_depth',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('session', 'longest_hold_down_time',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('session', 'free_text',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               nullable=True)
    op.alter_column('fish', 'en_name',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               nullable=True)
    op.alter_column('fish', 'he_name',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.create_index(op.f('idx_catch_user_id'), 'catch', ['user_id'], unique=False, postgresql_with={'deduplicate_items': 'true'})
    op.create_index(op.f('idx_catch_session_id'), 'catch', ['session_id'], unique=False)
    op.create_index(op.f('idx_catch_id'), 'catch', ['id'], unique=False)
    op.create_index(op.f('idx_catch_fish_id'), 'catch', ['fish_id'], unique=False)
    op.alter_column('catch', 'free_text',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.drop_table('message')
    op.drop_table('chat_participant')
    op.drop_table('guest')
    op.drop_table('chat_room')
    # ### end Alembic commands ###
