"""add catch media table and update catch model

Revision ID: c3659e507b43
Revises: 0f60493146fb
Create Date: 2026-03-27 13:41:26.120134

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c3659e507b43'
down_revision: Union[str, Sequence[str], None] = '0f60493146fb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('catch_media',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('catch_id', sa.UUID(), nullable=False),
    sa.Column('file_url', sa.String(), nullable=False),
    sa.Column('file_key', sa.String(), nullable=False),
    sa.Column('file_type', sa.String(), nullable=False),
    sa.Column('uploaded_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['catch_id'], ['catch.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_column('catch', 'image')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('catch', sa.Column('image', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.drop_table('catch_media')
    # ### end Alembic commands ###
